# Generated by Django 6.0 on 2026-01-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pair", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=500)),
                ("source", models.CharField(blank=True, max_length=200)),
                ("published_at", models.DateTimeField()),
                ("url", models.URLField(max_length=1000)),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="FXRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pair", models.CharField(max_length=10)),
                ("date", models.DateField()),
                ("rate", models.FloatField()),
            ],
            options={
                "ordering": ["-date", "pair"],
                "unique_together": {("pair", "date")},
            },
        ),
    ]
